### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Beastlinger7** [A-Baji/discordAI-modelizer#19]
I'm probably doing something dumb, but when the data_set.jsonl file is opened by the subprocess, it gives a filenotfound error. The parse_logs function seems to be giving me an empty data_set.jsonl file even though I have plenty in my logs.json file. Still not sure why it would give a filenotfounderror even if the file was empty.. its clearly there.

Traceback (most recent call last):
  File "discordai\command_line.py", line 396, in <module>
  File "discordai\command_line.py", line 361, in discordai
  File "discordai_modelizer\customize.py", line 48, in create_model
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1493, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[18260] Failed to execute script 'command_line' due to unhandled exception!

**Comment by A-Baji** [comment]
Could you give the exact command you are trying to run?

**Comment by Beastlinger7** [comment]
I was working with your discordAI project. Ran the command discordai model create -c 1053551350962724887 -u 444280476228780039 -t 10 -m 1000 -r middle --dirty

**Comment by Beastlinger7** [comment]
It generated 2 local files, 1053551350962724887_logs.json and 1053551350962724887_444280476228780039_data_set.jsonl

The log file has all the messages of the channel 105...887 and the data_set.jsonl file is empty.

**Comment by A-Baji** [comment]
Ah, the user input should be in the <username#id> format, not their actual uuid. 

For example: `example#1234`

If the username includes spaces, make sure to wrap it in quotes.

If you want, you can open a new issue for a feature request to be able to use uuid's as well.

**Comment by Beastlinger7** [comment]
Thank you, that did seem to fix the problem of the data set file being empty, it does indeed give a dataset now. However, I still get the same error.

INFO: Chat logs detected locally at C:\Users\me\AppData\Local\Adib Baji\discordai/1053551350962724887_logs.json... Skipping download.
INFO: Parsing chat logs into a openAI compatible dataset...
INFO: Cleaning up generated dataset...
Traceback (most recent call last):
  File "discordai\command_line.py", line 396, in <module>
  File "discordai\command_line.py", line 361, in discordai
  File "discordai_modelizer\customize.py", line 48, in create_model
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1493, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[12340] Failed to execute script 'command_line' due to unhandled exception!

**Comment by Beastlinger7** [comment]
I believe that this may be due to you using a space in the directory Adib Baji, or maybe the change from a backslash to a forwardslash in the path...

**Comment by A-Baji** [comment]
Yea, looks like an os path slash issue. Are you using the cli exe or the pip package? I've tested the exe on windows 10 myself and have not run into this issue.

Also I did not realize my name would appear as a directory like that. I'll get rid of it 😅

**Comment by Beastlinger7** [comment]
I am using the CLI exe, your latest release. 
Yeah, its the appdirs.user_data_dir function in config.py, where you just pass "author' (you). 

Changing that directory to something different will cause unexpected behavior for other users, who will find that they no longer have their previous datasets and that their discord bot token and openAI token are no longer configured.

**Comment by A-Baji** [comment]
Windows 10 or 11?

> Changing that directory to something different will cause unexpected behavior for other users, who will find that they no longer have their previous datasets and that their discord bot token and openAI token are no longer configured.

I agree, but I don't think there are enough users to warrant having to worry about backwards compatibility yet.

**Comment by Beastlinger7** [comment]
10

**Comment by A-Baji** [comment]
@Beastlinger7 Fixed in discordAI [1.2.0](https://github.com/A-Baji/discordAI/releases/tag/1.2.0) (modelizer 1.1.0).
It took a bit but I found the root of the issue. When trying to use the `openai` cli commands with `subprocess`, it searches for `openai` within your PATH, rather than using the one included in the package. It was easier to just remove/replace the usage entirely rather than figure out how to use the bundled `openai`.
